/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import utils.Config;
import utils.SpecialKernels;

/**
 *
 * @author Laptop
 */
public class ControlsPanel extends javax.swing.JPanel {
    RetinaPanel rp;
    /**
     * Creates new form ControlsPanel
     */
    public ControlsPanel(RetinaPanel rp) {
        this.rp=rp;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brightSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        contrastSlider = new javax.swing.JSlider();

        setBackground(new java.awt.Color(51, 51, 51));

        brightSlider.setMaximum(255);
        brightSlider.setMinimum(-255);
        brightSlider.setValue(0);
        brightSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brightSliderMouseDragged(evt);
            }
        });
        brightSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                brightSliderMouseReleased(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Brightness");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Contrast");

        contrastSlider.setMinimum(-100);
        contrastSlider.setValue(0);
        contrastSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                contrastSliderMouseDragged(evt);
            }
        });
        contrastSlider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                contrastSliderMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(brightSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
            .addComponent(contrastSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brightSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contrastSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void brightSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brightSliderMouseDragged
        // TODO add your handling code here:
        float value=(float)(brightSlider.getValue());
        Config.bright=value;
        jLabel1.setText("Brightness: "+value);
        rp.createImage(0, false);
    }//GEN-LAST:event_brightSliderMouseDragged

    private void contrastSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrastSliderMouseDragged
        // TODO add your handling code here:
        float value=(float)(contrastSlider.getValue()*0.01)+1;
        Config.contr=value;
        jLabel2.setText("Contrast: "+value);
        rp.createImage(0, false);
    }//GEN-LAST:event_contrastSliderMouseDragged

    private void contrastSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contrastSliderMouseReleased
        // TODO add your handling code here:
        rp.createImage(0, true);
    }//GEN-LAST:event_contrastSliderMouseReleased

    private void brightSliderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brightSliderMouseReleased
        // TODO add your handling code here:
        rp.createImage(0, true);
    }//GEN-LAST:event_brightSliderMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider brightSlider;
    private javax.swing.JSlider contrastSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
