/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Point;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import utils.layoutManager;

/**
 *
 * @author HumanoideFilms
 */
public class Frame extends javax.swing.JFrame {

    int index;
    String title;

    /**
     * Creates new form Frame
     */
    public Frame(int index) {
        this.index = index;
        initComponents();
        this.setLocation(layoutManager.points.get(index));

    }

    public void setImage(BufferedImage image, String title) {
        setVisible(true);
        if (title != null) {
            this.setTitle(title);
            this.title = title;
        } else {
            this.setTitle("cuayoyotolt");
        }
        jLabel1.setIcon(new ImageIcon(image));
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 273, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int x;
    int y;
    boolean lock;
    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        if (!lock) {
            x = -evt.getX();
            y = -evt.getY();
            lock = true;
        }
        this.setLocation(new Point(x + evt.getXOnScreen(), y + evt.getYOnScreen()));
        //System.out.println(x+" "+y);
    }//GEN-LAST:event_formMouseDragged

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        lock = false;
    }//GEN-LAST:event_formMouseReleased

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, "diste click alv"+this.getTitle());
        // Recoge el Clipboard del sistema.
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();

        // Recoge la imagen del JLabel.
        ImageIcon image = (ImageIcon) jLabel1.getIcon();

       // image.getIconHeight()
                //JOptionPane.showMessageDialog(null, "diste click alv "+image.getIconHeight());
        // Construye un Transferable con la imagen
        ImageSelection dh = new ImageSelection(image.getImage());
        

        // Pone la imagen en el Clipboard
        cb.setContents(dh, null);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
