/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.components;

import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.io.File;
import javax.swing.table.DefaultTableModel;
import utils.FileUtils;

/**
 *
 * @author HumanoideFilms
 */
public class ListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListPanel
     */
    public ListPanel() {
        initComponents();
    }

    int numCols;
    String clipboardString;
    String filePath;
    String extension;

    DefaultTableModel model;

    public void setColumnNames(String... names) {
        model = new DefaultTableModel(null, names);
        jTable1.setModel(model);
        numCols = names.length;
    }

    public void setClipboardString(String string) {
        clipboardString = string;
    }

    public void setFilePath(String path, String extension) {
        filePath = path;
        this.extension = extension;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        removeButton = new javax.swing.JButton();
        duplicateButton = new javax.swing.JButton();
        copyButton = new javax.swing.JButton();
        pasteButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        dowbButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new java.awt.GridLayout(8, 1, 10, 10));

        addButton.setBackground(new java.awt.Color(60, 88, 94));
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add row");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel1.add(addButton);

        removeButton.setBackground(new java.awt.Color(60, 88, 94));
        removeButton.setForeground(new java.awt.Color(255, 255, 255));
        removeButton.setText("Delete row");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(removeButton);

        duplicateButton.setBackground(new java.awt.Color(45, 69, 86));
        duplicateButton.setForeground(new java.awt.Color(255, 255, 255));
        duplicateButton.setText("Duplicate");
        duplicateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplicateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(duplicateButton);

        copyButton.setBackground(new java.awt.Color(45, 69, 86));
        copyButton.setForeground(new java.awt.Color(255, 255, 255));
        copyButton.setText("Copy");
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });
        jPanel1.add(copyButton);

        pasteButton.setBackground(new java.awt.Color(45, 69, 86));
        pasteButton.setForeground(new java.awt.Color(255, 255, 255));
        pasteButton.setText("Paste");
        pasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pasteButton);

        upButton.setBackground(new java.awt.Color(60, 88, 94));
        upButton.setForeground(new java.awt.Color(255, 255, 255));
        upButton.setText("Up");
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });
        jPanel1.add(upButton);

        dowbButton.setBackground(new java.awt.Color(60, 88, 94));
        dowbButton.setForeground(new java.awt.Color(255, 255, 255));
        dowbButton.setText("Down");
        dowbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dowbButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dowbButton);

        jButton1.setBackground(new java.awt.Color(45, 69, 86));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(75, 75, 75));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents
    boolean empty = true;
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        Object[] rowData = new Object[numCols];
        int row = jTable1.getSelectedRow();
        for (int i = 0; i < numCols; i++) {
            rowData[i] = null;
        }
        model.addRow(rowData);
        if (!empty && row != -1) {
            //int row = jTable1.getSelectedRow();
            int s = jTable1.getRowCount();
            for (int i = s - 1; i > row; i--) {
                for (int j = 0; j < jTable1.getColumnCount(); j++) {
                    jTable1.setValueAt(jTable1.getValueAt(i - 1, j), i, j);
                }
            }

            for (int j = 0; j < jTable1.getColumnCount(); j++) {
                jTable1.setValueAt(rowData[j], row + 1, j);
            }
            jTable1.setRowSelectionInterval(jTable1.getSelectedRow() + 1, jTable1.getSelectedRow() + 1);
        } else {
            jTable1.setRowSelectionInterval(0, 0);
        }
        empty = false;
    }//GEN-LAST:event_addButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        // TODO add your handling code here:        
        int row = jTable1.getSelectedRow();
        if (row != -1 && !empty) {
            model.removeRow(jTable1.getSelectedRow());
            if (jTable1.getRowCount() <= 0) {
                empty = true;
            } else {
                if (row > 0) {
                    jTable1.setRowSelectionInterval(row - 1, row - 1);
                } else {
                    jTable1.setRowSelectionInterval(0, 0);
                }
            }

        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void duplicateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicateButtonActionPerformed
        // TODO add your handling code here:
        Object[] rowData = new Object[numCols];
        for (int i = 0; i < numCols; i++) {
            rowData[i] = null;
        }
        model.addRow(rowData);
        int row = jTable1.getSelectedRow();
        int s = jTable1.getRowCount();
        for (int i = s - 1; i > row; i--) {
            for (int j = 0; j < jTable1.getColumnCount(); j++) {
                jTable1.setValueAt(jTable1.getValueAt(i - 1, j), i, j);
            }
        }

        for (int j = 0; j < jTable1.getColumnCount(); j++) {
            jTable1.setValueAt(jTable1.getValueAt(row, j), row + 1, j);
        }
        jTable1.setRowSelectionInterval(jTable1.getSelectedRow() + 1, jTable1.getSelectedRow() + 1);
    }//GEN-LAST:event_duplicateButtonActionPerformed

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        Object[] rowData = new Object[numCols];
        for (int i = 0; i < numCols; i++) {
            rowData[i] = jTable1.getValueAt(row, i);
        }
        if (row < jTable1.getRowCount()) {
            if (jTable1.getSelectedRow() > 0) {
                for (int i = 0; i < jTable1.getColumnCount(); i++) {
                    jTable1.setValueAt(jTable1.getValueAt(row - 1, i), row, i);
                }
                for (int i = 0; i < jTable1.getColumnCount(); i++) {
                    jTable1.setValueAt(rowData[i], row - 1, i);
                }

                jTable1.setRowSelectionInterval(row - 1, row - 1);
            }
        }
    }//GEN-LAST:event_upButtonActionPerformed

    private void dowbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dowbButtonActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
        Object[] rowData = new Object[numCols];
        for (int i = 0; i < numCols; i++) {
            rowData[i] = jTable1.getValueAt(row, i);
        }
        if (row < jTable1.getRowCount() - 1) {
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                jTable1.setValueAt(jTable1.getValueAt(row + 1, i), row, i);
            }
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                jTable1.setValueAt(rowData[i], row + 1, i);
            }
            if (jTable1.getSelectedRow() < jTable1.getRowCount()) {
                jTable1.setRowSelectionInterval(row + 1, row + 1);
            }
        }
    }//GEN-LAST:event_dowbButtonActionPerformed

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        // TODO add your handling code here:
        copy();
    }//GEN-LAST:event_copyButtonActionPerformed

    public void copy() {
        try {
            int row = jTable1.getSelectedRow();
            String cString = clipboardString + " ";
            for (int i = 0; i < jTable1.getColumnCount(); i++) {
                cString = cString + jTable1.getValueAt(row, i);
                if (i < jTable1.getColumnCount() - 1) {
                    cString = cString + " ";
                }
            }
            StringSelection stringSelection = new StringSelection(cString);
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            clipboard.setContents(stringSelection, null);
        } catch (Exception ex) {
        }
    }
    
    private void pasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteButtonActionPerformed
        // TODO add your handling code here:
        Clipboard cb = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable t = cb.getContents(this);

        DataFlavor dataFlavorStringJava;
        try {
            dataFlavorStringJava = new DataFlavor("application/x-java-serialized-object; class=java.lang.String");
            if (t.isDataFlavorSupported(dataFlavorStringJava)) {
                String texto = (String) t.getTransferData(dataFlavorStringJava);
                if (texto.contains(clipboardString)) {
                    int row = jTable1.getSelectedRow();
                    String values[] = texto.split(" ");
                    for (int i = 0; i < jTable1.getColumnCount(); i++) {
                        jTable1.setValueAt(values[i + 1], row, i);
                    }
                }
            }
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_pasteButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (filePath != null && extension != null) {
            save();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void save() {
        String saveString = "";
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (CompleteRow(i)) {
                for (int j = 0; j < jTable1.getColumnCount(); j++) {
                    saveString = saveString + jTable1.getValueAt(i, j);
                    if (j < jTable1.getColumnCount() - 1) {
                        saveString = saveString + " ";
                    }
                }
                if (i < jTable1.getRowCount() - 1) {
                    saveString = saveString + "\n";
                }
            }
        }
        FileUtils.write(filePath, saveString, extension);
    }

    public void loadFile() {
        File file = new File(filePath + "." + extension);
        if (file.exists()) {
            String fileContent = FileUtils.readFile(file);
            String lines[] = fileContent.split("\\n");
            if (lines.length > 0) {
                empty = false;
            }
            for (int i = 0; i < lines.length; i++) {
                Object[] rowData = new Object[numCols];
                int row = jTable1.getSelectedRow();
                for (int k = 0; k < numCols; k++) {
                    rowData[k] = null;
                }
                model.addRow(rowData);
            }
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                String values[] = lines[i].split(" ");
                for (int j = 0; j < jTable1.getColumnCount(); j++) {
                    jTable1.setValueAt(values[j], i, j);
                }
            }
            jTable1.setRowSelectionInterval(0, 0);
        }
    }

    public boolean CompleteRow(int row) {
        boolean band = true;
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            if (jTable1.getValueAt(row, i) == null) {
                band = false;
                break;
            }
        }
        return band;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton copyButton;
    private javax.swing.JButton dowbButton;
    private javax.swing.JButton duplicateButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pasteButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables
}
