/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package generator;

import java.awt.Graphics;
import java.awt.image.BufferedImage;

/**
 *
 * @author HumanoideFilms
 */
public class visualizerTest extends javax.swing.JFrame {

    /**
     * Creates new form visualizerTest
     */
    public visualizerTest() {
        initComponents();
    }

    BufferedImage img;
    public void setImage(BufferedImage image, String title) {
        setVisible(true);
        if (title != null) {
            this.setTitle(title);
        } else {
            this.setTitle("cuayoyotolt");
        }
        img=image;
        repaint();
    }

    public void paint(Graphics g) {
        if(img!=null)
        g.drawImage(img, 0, 0, null);
    }

    public void setFrameSize(int s) {
        this.setSize(s, s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
